version: '2'

services:
  react-client:
    build:
      context: ./react-frontend/
      dockerfile: local.Dockerfile
    volumes:
      - './react-frontend/:/usr/src/app'
      - '/usr/src/app/node_modules'
      - './dataset:/usr/src/app/public/dataset'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    image: react_frontend
    container_name: ivist_app
